name: Debug-CI
on: 
  workflow_dispatch:
  push:

        
  fastai-integration-test:
    runs-on: ubuntu-latest
    env:
      download: "true"
    strategy:
      matrix:
        nb: ['[0-1]', '[2-3]', '[4-5]','[6-7]', '[8-9]']
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: clone this branch [fastcore]
      uses: actions/checkout@v3
      with:
        path: fastcore/
        
    - name: clone fastai
      uses: actions/checkout@v3
      with:
        repository: 'fastai/fastai'
        path: fastai
        
    - name: Install libraries
      run: |
        pip3 install -Uqq nbdev
        cd fastai && pip3 install -Ue ".[dev]"
        cd ../fastcore && pip3 install -Ue .[dev]

    - name: check for cache hit
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.fastai/data
        key: 'fastai-test-data-v5'

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: download data
      if: env.download == 'true' && steps.cache.outputs.cache-hit != 'true'
      run: |
        ipython /root/download_testdata.py
        mkdir -p $HOME/.fastai/data
        find $HOME/.fastai/archive/ -name "*.tgz" -exec tar -xzvf {} -C $HOME/.fastai/data \;
          
    - name: Test fastai notebooks
      run: |
        cd fastai
        nbdev_test_nbs --flags '' --n_workers 3 --pause 1.5 --fname "nbs/[0-9]${{matrix.nb}}*.ipynb"
