name: docs
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
      - requested
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: fastai/nbdev
    defaults:
      run:
        shell: bash
        working-directory: /root
    steps:
    - name: checkout contents of PR
      uses: actions/checkout@v2

    - name: Create docs
      id: docs
      #env:
      #  HOME: /root
      run: |
        . ~/.condainit
        conda activate
        pip install torchvision
        cp -r docs_src docs
        nbdev_build_docs

    - name: setup directories for Jekyll build
      run: |
        rm -rf docs/_site
        chmod -R 777 docs
        cd docs 
        #chmod -R u+rwx 
        jekyll build -V --strict_front_matter --trace
      env:
        JEKYLL_ENV: 'production'

    - name: rsync to dreamhost
      uses: fastai/workflows/rsync@master
      with:
        hostname: ps625762.dreamhostps.com
        ssh_key: ${{ secrets.DH_KEY }}
        dest_path: "fastcore.fast.ai/"
        username: jeremyphoward
