name: docs
env:
  HOME: /root
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: fastai/fastai
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: fastai/workflows/conda-env@master
    - name: Create docs
      #id: docs
      env:
        JEKYLL_ENV: 'production'
        SSH_KEY: ${{ secrets.DH_KEY }}
      run: |
        cp -r docs_src docs
        nbdev_build_docs
        cd docs 
        jekyll build --strict_front_matter
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ls _site
        rsync -az _site/ jeremyphoward@ps625762.dreamhostps.com:fastcore.fast.ai/
