name: docs
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
      - requested
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: fastai/fastai
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout contents of PR
      uses: actions/checkout@v2

    - name: Create docs
      id: docs
      env:
        HOME: /root
        JEKYLL_ENV: 'production'
        SSH_KEY: ${{ secrets.DH_KEY }}
      run: |
        . ~/.bashrc
        cp -r docs_src docs
        nbdev_build_docs
        cd docs 
        jekyll build --strict_front_matter
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        rsync -az _site/ jeremyphoward@ps625762.dreamhostps.com:fastcore.fast.ai/
